import { Script } from './types';

export const MOCK_SCRIPTS: Script[] = [
  {
    id: "script_1",
    title: "Blox Fruits Auto-Farm Pro",
    description: "Fully automated level farming, quest completion, and chest collection. Advanced anti-ban protection included.",
    price: 19.99,
    game: "Blox Fruits",
    tags: ["Auto-Farm", "Combat", "Raid", "Best-Seller"],
    features: ["Instant Quest", "Auto-Stat", "Safe Mode"],
    authorId: "vendor_1",
    authorName: "NexusDev",
    thumbnailUrl: "https://images.unsplash.com/photo-1614850523296-d8c1af93d400?auto=format&fit=crop&q=80&w=400",
    isPremium: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    viewCount: 1540,
    purchaseCount: 1420,
    rating: 4.9,
    reviewCount: 32
  },
  {
    id: "script_2",
    title: "Arsenal ESP & Silent Aim",
    description: "High-precision silent aimbot with customizable ESP colors and FOV. Undetected for 6 months.",
    price: 12.50,
    game: "Arsenal",
    tags: ["PvP", "Aimbot", "ESP", "Visual"],
    features: ["Silent Aim", "Wallhack", "Fov Circle"],
    authorId: "vendor_3",
    authorName: "PhantomX",
    thumbnailUrl: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&q=80&w=400",
    isPremium: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    viewCount: 3200,
    purchaseCount: 850,
    rating: 4.8,
    reviewCount: 124
  },
  {
    id: "script_3",
    title: "Pet Sim 99 Multi-Instance Hub",
    description: "Run up to 10 instances with shared inventory management. Auto-egg opening and trading terminal.",
    price: 45.00,
    game: "Pet Simulator 99",
    tags: ["Economy", "Auto-Farm", "Multi-Box"],
    features: ["Instance Sync", "Auto-Clicker", "Inventory Export"],
    authorId: "vendor_2",
    authorName: "CyberPet",
    thumbnailUrl: "https://images.unsplash.com/photo-1627398242454-45a1465c2479?auto=format&fit=crop&q=80&w=400",
    isPremium: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    viewCount: 890,
    purchaseCount: 112,
    rating: 4.5,
    reviewCount: 15
  },
  {
    id: "script_4",
    title: "Universal Admin Commands",
    description: "Over 200+ commands for any game. Fly, Noclip, God-mode, and Client-side destruction tools.",
    price: 0.00,
    game: "Universal",
    tags: ["Admin", "Utility", "Movement", "Free"],
    features: ["Custom UI", "Saved Commands", "Fast Execution"],
    authorId: "vendor_4",
    authorName: "CommandMaster",
    thumbnailUrl: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&q=80&w=400",
    isPremium: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    viewCount: 12000,
    purchaseCount: 5400,
    rating: 4.2,
    reviewCount: 560
  },
  {
    id: "script_5",
    title: "MM2 Auto-Sheriff & ESP",
    description: "Instantly win as Sheriff and see Murders through walls. Dynamic hitboxes and coin farming.",
    price: 8.99,
    game: "MM2",
    tags: ["PvP", "ESP", "Economy"],
    features: ["Silent Aim", "Instant Coin", "Auto-Victory"],
    authorId: "vendor_1",
    authorName: "NexusDev",
    thumbnailUrl: "https://images.unsplash.com/photo-1542751110-97427bbecf20?auto=format&fit=crop&q=80&w=400",
    isPremium: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    viewCount: 4500,
    purchaseCount: 920,
    rating: 4.7,
    reviewCount: 89
  }
];
